server.port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password: <blank>
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        ddl-auto: update
    defer-datasource-initialization: true
  logging:
    level:
      root: DEBUG