server.port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        ddl-auto: create
    defer-datasource-initialization: false
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql.BasicBinder: TRACE
      root: DEBUG
  flyway.locations: db